[package]
name = "server"
version = "0.1.0"
authors = ["Wally Yang <wallyyang28@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
wa-fsp = { path = "..", version = "0.1.0" }